"use client"

import { useState } from "react"
import { Search, Calendar, User, Download, ChevronDown } from "lucide-react"
import { Input } from "@/components/ui/input"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Badge } from "@/components/ui/badge"
import { createClient } from "@/lib/supabase/client"
import { useRouter } from "next/navigation"
import { toast } from "sonner"

export type QuotationStatus = 'pending' | 'negotiating' | 'approved' | 'rejected' | 'on_hold'

interface Quotation {
  id: string
  quotation_number: string
  customer_name: string
  grand_total: number
  created_at: string
  pdf_url: string | null
  status: QuotationStatus
  profiles: { full_name: string }
}

const statusColors: Record<QuotationStatus, string> = {
  pending: "bg-gray-100 text-gray-800 hover:bg-gray-200 border-gray-200",
  negotiating: "bg-blue-100 text-blue-800 hover:bg-blue-200 border-blue-200",
  approved: "bg-green-100 text-green-800 hover:bg-green-200 border-green-200",
  rejected: "bg-red-100 text-red-800 hover:bg-red-200 border-red-200",
  on_hold: "bg-amber-100 text-amber-800 hover:bg-amber-200 border-amber-200",
}

const statusLabels: Record<QuotationStatus, string> = {
  pending: "Pending",
  negotiating: "Negotiating",
  approved: "Approved",
  rejected: "Rejected",
  on_hold: "On Hold",
}

export default function QuotationsClient({ initialQuotations }: { initialQuotations: Quotation[] }) {
  const [search, setSearch] = useState("")
  const [updatingId, setUpdatingId] = useState<string | null>(null)
  
  const router = useRouter()
  const supabase = createClient()

  const filtered = initialQuotations.filter(
    (q) =>
      q.customer_name?.toLowerCase().includes(search.toLowerCase()) ||
      q.quotation_number?.toLowerCase().includes(search.toLowerCase()) ||
      q.profiles?.full_name?.toLowerCase().includes(search.toLowerCase())
  )

  const handleStatusChange = async (id: string, newStatus: QuotationStatus) => {
    setUpdatingId(id)
    try {
      const { error } = await supabase
        .from('quotations')
        .update({ status: newStatus })
        .eq('id', id)

      if (error) throw error
      
      toast.success("Status updated successfully")
      router.refresh()
    } catch (error) {
      console.error(error)
      toast.error("Failed to update status")
    } finally {
      setUpdatingId(null)
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Quotation Tracking</h1>
        <p className="text-muted-foreground">Monitor all quotations generated by your sales team.</p>
      </div>
      <div className="flex flex-col gap-4 md:flex-row md:items-center">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Search by customer, number, or salesperson..."
            className="pl-9"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
      </div>
      <div className="rounded-xl border bg-white shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="whitespace-nowrap">Number</TableHead>
                <TableHead className="whitespace-nowrap">Customer</TableHead>
                <TableHead className="whitespace-nowrap">Salesperson</TableHead>
                <TableHead className="whitespace-nowrap">Amount</TableHead>
                <TableHead className="whitespace-nowrap">Status</TableHead>
                <TableHead className="whitespace-nowrap">Date</TableHead>
                <TableHead className="text-right whitespace-nowrap">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filtered.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={7} className="h-24 text-center">No quotations found.</TableCell>
                </TableRow>
              ) : (
                filtered.map((q) => (
                  <TableRow key={q.id}>
                    <TableCell className="font-mono text-xs font-semibold">{q.quotation_number}</TableCell>
                    <TableCell><div className="font-medium">{q.customer_name}</div></TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <User className="h-3 w-3 text-muted-foreground" />
                        <span className="text-sm">{q.profiles?.full_name || "Unknown"}</span>
                      </div>
                    </TableCell>
                    <TableCell className="font-bold">₹{q.grand_total?.toLocaleString()}</TableCell>
                    <TableCell>
                      <DropdownMenu>
                        <DropdownMenuTrigger disabled={updatingId === q.id} className="focus:outline-none disabled:opacity-50">
                          <Badge variant="outline" className={`flex items-center gap-1 cursor-pointer transition-colors ${statusColors[q.status || 'pending']}`}>
                            {statusLabels[q.status || 'pending']}
                            <ChevronDown className="h-3 w-3 opacity-50" />
                          </Badge>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="start">
                          {(Object.keys(statusLabels) as QuotationStatus[]).map((status) => (
                            <DropdownMenuItem
                              key={status}
                              onClick={() => handleStatusChange(q.id, status)}
                              className="cursor-pointer font-medium"
                            >
                              <div className={`w-2 h-2 rounded-full mr-2 ${status === 'pending' ? 'bg-gray-500' : status === 'negotiating' ? 'bg-blue-500' : status === 'approved' ? 'bg-green-500' : status === 'rejected' ? 'bg-red-500' : 'bg-amber-500'}`} />
                              {statusLabels[status]}
                            </DropdownMenuItem>
                          ))}
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </TableCell>
                    <TableCell className="text-muted-foreground">
                      <div className="flex items-center gap-2">
                        <Calendar className="h-3 w-3" />
                        <span suppressHydrationWarning className="text-xs">{new Date(q.created_at).toLocaleDateString()}</span>
                      </div>
                    </TableCell>
                    <TableCell className="text-right">
                      {q.pdf_url && (
                        <a href={q.pdf_url} target="_blank" rel="noopener noreferrer"
                          className="inline-flex items-center gap-2 rounded-md border px-3 py-1 text-xs font-medium transition-colors hover:bg-gray-50">
                          <Download className="h-3 w-3" /> View PDF
                        </a>
                      )}
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  )
}
